# Backend/tasks/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import TaskViewSet, dashboard_stats

# The DefaultRouter automatically generates the CRUD URLs for the ViewSet
router = DefaultRouter()
router.register(r'tasks', TaskViewSet, basename='task')

urlpatterns = [
    # This includes all the routes generated by the router (e.g., /tasks/, /tasks/<id>/)
    path('', include(router.urls)),
    
    # Custom endpoint for dashboard stats
    path('dashboard-stats/', dashboard_stats, name='dashboard-stats'),
]